[supervisord]
nodaemon=true
user=www-data
logfile=/tmp/supervisord.log
loglevel=debug
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[program:httpd]
command = /opt/cnaas/venv/bin/uvicorn cnaas_httpd.main:app --proxy-headers --port 8000
directory=/opt/cnaas/venv/cnaas-httpd/src
autorestart=true

[program:nginx]
command=/opt/cnaas/http.sh
autorestart=true